<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function site_info_extras_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
	$config = \Drupal::config('site_info.extras');
	
	$form['extras'] = [
		'#type' => 'details',
		'#title' => t('Extras'),
		'#open' => TRUE
	];
	$form['extras']['site_api_key'] = [
	   '#type' => 'textfield',
	   '#title' => t("Site API Key."),
	   '#default_value' => $config->get('site_api_key'),
	];

	if ($config->get('site_api_key')) {
		$form['actions']['submit']['#value'] = t('Update Configurations');
	}
	
	// Add custom submit handeler.
	$form['actions']['submit']['#submit'][]  = 'site_info_extras_submit_handler';
}

/**
 * Custom submit handler.
 */
function site_info_extras_submit_handler(&$form, FormStateInterface $form_state) {
   $config = \Drupal::service('config.factory')->getEditable('site_info.extras');
   $key = $form_state->getValue('site_api_key');
   $config->set('site_api_key', $key)->save();
   drupal_set_message('Site API Key has been saved.');
}